### ISSUE TITLE
get_historical_lmp takes a market object, not the default string

### ISSUE THREAD

**Issue by arao53** [kmax12/isodata#26]
The function for `get_historical_lmp` prescribes a string that represents the market (e.g."REAL_TIME_HOURLY") but the conditional in the function takes an object (e.g. `self.REAL_TIME_HOURLY`)

I got around this with the following: 

`date= "June 1, 2020"`
`rth=isodata.base.Markets.REAL_TIME_HOURLY`
`data=caiso.get_historical_lmp(date=date, market=rth, nodes=None)`

I found this example for CAISO, but I'm not sure if it persists across the other ISOs.

**Comment by arao53** [comment]
"REAL_TIME_HOURLY" might be returning "REAL_TIME_15_MIN" instead.
![image](https://user-images.githubusercontent.com/59095986/185221632-3c738be8-8c41-49a8-bced-1f84928461b4.png)

**Comment by kmax12** [comment]
I made a release yesterday (v0.6.0), that cleaned up this code a bit so you can use string or object

```
>>> from isodata import Markets
>>> caiso.get_historical_lmp(date=date, market=Markets.REAL_TIME_HOURLY, locations=None)
```

works the same as 

```
>>> caiso.get_historical_lmp(date=date, market="REAL_TIME_HOURLY", locations=None)
```

Also, note that the `nodes` parameter changed to `locations` to make it more general purpose

if you need to upgrade  you can run

```
pip install --upgrade isodata
```
you can confirm it upgraded like this 

```
>>> import isodata
>>> isodata.__version__
'0.6.0'
```

**Comment by arao53** [comment]
The change for the market/location parameter works great now. Thanks for addressing this so quickly! 

The remaining (minor) issue is that "REAL_TIME_HOURLY" seems to be returning "REAL_TIME_15_MIN". I just changed the indexing in post.
```
>>> data = caiso.get_historical_lmp()[::4]
```

**Comment by kmax12** [comment]
I looked into it more and "REAL_TIME_HOURLY" is probably the wrong name for the market.

It is actually returning the results for the HASP (hourly ahead scheduling process) market in CAISO. I'm not very familiar with it myself, so im looking for a good source that explains it to share

But, my understanding is that bids get placed every hour, but the actually settles every fifteen minutes which is why you get 4 prices an hour.
