### ISSUE TITLE
ISO.get_historical_lmp : add feature to query historical time period

### ISSUE THREAD

**Issue by m4rz910** [kmax12/isodata#52]
Hey, would be nice to be able to pull large time spans instead of individual days at a time. Thanks!

**Comment by m4rz910** [comment]
In general getting a key error "items" when I run the code...
``
o = isodata.PJM()
o.get_historical_lmp(date='1/1/2022', market="REAL_TIME_5_MIN", locations='ALL')
``

**Comment by kmax12** [comment]
Good timing since I'm working on this in this pr to support date ranges: #53. I will add support for PJM ASAP (hopefully later today) and release it. 

In terms of the key error, there are 2 issues.

1.  "ALL" isn't supported for PJM. If you pass `None` or don't provide parameter, it will return all the Hubs. Alternatively, you can call `pjm.get_pnode_ids()` to see all the valid pnode ids. 
2. The PJM API  doesn't appear to have data going back before 4/17/2022. It's possible it is a 6 month rolling window. I'll need to look into more, but let me know if you are able to access earlier data anywhere. 

Here's a query that works for me

```
o = isodata.PJM()
o.get_historical_lmp(date='4/17/2022', market="REAL_TIME_5_MIN", locations=None)
```
```
	Time	Market	Location	Location Name	Location Type	LMP	Energy	Congestion	Loss
0	2022-04-17 00:00:00-04:00	REAL_TIME_5_MIN	51217	EASTERN HUB	HUB	44.378613	45.3	-0.725136	-0.196251
1	2022-04-17 00:00:00-04:00	REAL_TIME_5_MIN	51287	WEST INT HUB	HUB	45.638333	45.3	0.364444	-0.026111
2	2022-04-17 00:00:00-04:00	REAL_TIME_5_MIN	51288	WESTERN HUB	HUB	44.359686	45.3	-0.601354	-0.338960
3	2022-04-17 00:00:00-04:00	REAL_TIME_5_MIN	4669664	NEW JERSEY HUB	HUB	44.252114	45.3	-0.676695	-0.371191
4	2022-04-17 00:00:00-04:00	REAL_TIME_5_MIN	33092311	CHICAGO GEN HUB	HUB	44.118462	45.3	0.088923	-1.270462
...	...	...	...	...	...	...	...	...	...
3463	2022-04-18 00:00:00-04:00	REAL_TIME_5_MIN	34497125	AEP GEN HUB	HUB	58.237632	56.7	1.995789	-0.458158
3464	2022-04-18 00:00:00-04:00	REAL_TIME_5_MIN	34497127	AEP-DAYTON HUB	HUB	59.287602	56.7	1.907586	0.680015
3465	2022-04-18 00:00:00-04:00	REAL_TIME_5_MIN	34497151	OHIO HUB	HUB	59.307808	56.7	1.819914	0.787894
3466	2022-04-18 00:00:00-04:00	REAL_TIME_5_MIN	35010337	DOMINION HUB	HUB	62.141569	56.7	3.989563	1.452006
3467	2022-04-18 00:00:00-04:00	REAL_TIME_5_MIN	116013751	ATSI GEN HUB	HUB	57.804091	56.7	1.209318	-0.105227
```

**Comment by kmax12** [comment]
sorry, the issue isn't the historical data, it's with the p node ids at earlier dates. will post more info shortly

**Comment by kmax12** [comment]
found the documentation for "archived" data and working on implementing around it in #54.

sharing below in case it's of interest

<img width="666" alt="image" src="https://user-images.githubusercontent.com/371792/197076827-26e7a737-2f3f-4b1a-876e-1ca920a601f4.png">

**Comment by m4rz910** [comment]
Appreciate you looking into this and can appreciate the challenge. Probably part of the reason certain other services stopped providing subhourly data... Thanks for the quick response!

**Comment by kmax12** [comment]
the PJM API has a ton of data, but lots of edge cases to handle to support querying arbitrary date ranges and filter settings. anyways, it's now in isodata, so hopefully know else has to go through that again :)

here's an example usage notebook: https://github.com/kmax12/isodata/blob/main/Examples/PJM%20LMP%20Data.ipynb
