### ISSUE TITLE
Real-time price data

### ISSUE THREAD

**Issue by adam-a-a** [kmax12/isodata#6]
While there seems to be functionality for grabbing day-ahead electricity prices, I'm not sure there is any functionality on collecting real-time pricing data yet. Adding this functionality could be desirable.

EDIT: Thank you for taking on this effort!

**Comment by kmax12** [comment]
Working on adding this now. Made some good progress, but need fill in some gaps and to make sure everything is well tested. Put a branch and pr up [here](https://github.com/kmax12/isodata/pull/7) if you want to follow up along. 

Is there a particular market and iso you are interested in? I can prioritize that and merge it in
